### ISSUE TITLE
i m getting error when  try to run "python3 train_ssd.py --dataset-type=voc --data=data/weldr/ --model-dir=models/model0110 --batch-size=2 --workers=5 --epochs=500"

### ISSUE THREAD

**Issue by kmlrohin1** [mailrocketsystems/jetson-train#1]
Traceback (most recent call last):
  File "train_ssd.py", line 13, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/kml/rohin/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 1, in <module>
    import tensorboard
  File "/home/kml/rohin/lib/python3.8/site-packages/tensorboard/__init__.py", line 4, in <module>
    from .writer import FileWriter, SummaryWriter
  File "/home/kml/rohin/lib/python3.8/site-packages/tensorboard/writer.py", line 28, in <module>
    from .summary import scalar, histogram, image, audio, text
  File "/home/kml/rohin/lib/python3.8/site-packages/tensorboard/summary/__init__.py", line 22, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "/home/kml/rohin/lib/python3.8/site-packages/tensorboard/summary/v1.py", line 21, in <module>
    from tensorboard.plugins.audio import summary as _audio_summary
  File "/home/kml/rohin/lib/python3.8/site-packages/tensorboard/plugins/audio/summary.py", line 34, in <module>
    from tensorboard.plugins.audio import metadata
  File "/home/kml/rohin/lib/python3.8/site-packages/tensorboard/plugins/audio/metadata.py", line 18, in <module>
    from tensorboard.compat.proto import summary_pb2
  File "/home/kml/rohin/lib/python3.8/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import histogram_pb2 as tensorboard_dot_compat_dot_proto_dot_histogram__pb2
  File "/home/kml/rohin/lib/python3.8/site-packages/tensorboard/compat/proto/histogram_pb2.py", line 18, in <module>
    DESCRIPTOR = _descriptor.FileDescriptor(
  File "/home/kml/rohin/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 1024, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorboard/compat/proto/histogram.proto":
  tensorboard.HistogramProto.min: "tensorboard.HistogramProto.min" is already defined in file "tensorboard/src/summary.proto".
  tensorboard.HistogramProto.max: "tensorboard.HistogramProto.max" is already defined in file "tensorboard/src/summary.proto".
  tensorboard.HistogramProto.num: "tensorboard.HistogramProto.num" is already defined in file "tensorboard/src/summary.proto".
  tensorboard.HistogramProto.sum: "tensorboard.HistogramProto.sum" is already defined in file "tensorboard/src/summary.proto".
  tensorboard.HistogramProto.sum_squares: "tensorboard.HistogramProto.sum_squares" is already defined in file "tensorboard/src/summary.proto".
  tensorboard.HistogramProto.bucket_limit: "tensorboard.HistogramProto.bucket_limit" is already defined in file "tensorboard/src/summary.proto".
  tensorboard.HistogramProto.bucket: "tensorboard.HistogramProto.bucket" is already defined in file "tensorboard/src/summary.proto".
  tensorboard.HistogramProto: "tensorboard.HistogramProto" is already defined in file "tensorboard/src/summary.proto".

**Comment by harry20011** [comment]
Make sure you use python 3.6 (i use 3.6.9). Also if that doesnt work download and get the dependicies of the original jetson inference github

**Comment by kmlrohin1** [comment]
thankyou harry that worked for me
