### ISSUE TITLE
Unable to train the data set

### ISSUE THREAD

**Issue by GirishPawar1999** [mailrocketsystems/jetson-train#2]
LOG:
(Train) D:\Gujarat Fertilizers\Traing\jetson-train-main\jetson-train-main>python train_ssd.py --dataset-type=voc --data=data/model0110/ --model-dir=models/model0110 --batch-size=2 --workers=5 --epochs=500
2023-10-18 12:49:22 - Namespace(balance_data=False, base_net=None, base_net_lr=0.001, batch_size=2, checkpoint_folder='models/model0110', dataset_type='voc', datasets=['data/model0110/'], debug_steps=10, extra_layers_lr=None, freeze_base_net=False, freeze_net=False, gamma=0.1, log_level='info', lr=0.01, mb2_width_mult=1.0, milestones='80,100', momentum=0.9, net='mb1-ssd', num_epochs=500, num_workers=5, pretrained_ssd='models/mobilenet-v1-ssd-mp-0_675.pth', resolution=300, resume=None, scheduler='cosine', t_max=100, use_cuda=True, validation_epochs=1, validation_mean_ap=False, weight_decay=0.0005)
2023-10-18 12:49:22 - model resolution 300x300
2023-10-18 12:49:22 - SSDSpec(feature_map_size=19, shrinkage=16, box_sizes=SSDBoxSizes(min=60, max=105), aspect_ratios=[2, 3])
2023-10-18 12:49:22 - SSDSpec(feature_map_size=10, shrinkage=32, box_sizes=SSDBoxSizes(min=105, max=150), aspect_ratios=[2, 3])
2023-10-18 12:49:22 - SSDSpec(feature_map_size=5, shrinkage=64, box_sizes=SSDBoxSizes(min=150, max=195), aspect_ratios=[2, 3])
2023-10-18 12:49:22 - SSDSpec(feature_map_size=3, shrinkage=100, box_sizes=SSDBoxSizes(min=195, max=240), aspect_ratios=[2, 3])
2023-10-18 12:49:22 - SSDSpec(feature_map_size=2, shrinkage=150, box_sizes=SSDBoxSizes(min=240, max=285), aspect_ratios=[2, 3])
2023-10-18 12:49:22 - SSDSpec(feature_map_size=1, shrinkage=300, box_sizes=SSDBoxSizes(min=285, max=330), aspect_ratios=[2, 3])
2023-10-18 12:49:22 - Prepare training datasets.
2023-10-18 12:49:23 - VOC Labels read from file: ('BACKGROUND', 'banna')
2023-10-18 12:49:23 - Stored labels into file models/model0110\labels.txt.
2023-10-18 12:49:23 - Train dataset size: 111
2023-10-18 12:49:23 - Prepare Validation datasets.
2023-10-18 12:49:23 - VOC Labels read from file: ('BACKGROUND', 'banna')
2023-10-18 12:49:23 - Validation dataset size: 12
2023-10-18 12:49:23 - Build network.
2023-10-18 12:49:23 - Init from pretrained ssd models/mobilenet-v1-ssd-mp-0_675.pth
2023-10-18 12:49:23 - Took 0.07 seconds to load the model.
2023-10-18 12:49:23 - Learning rate: 0.01, Base net learning rate: 0.001, Extra Layers learning rate: 0.01.
2023-10-18 12:49:23 - Uses CosineAnnealingLR scheduler.
2023-10-18 12:49:23 - Start training from epoch 0.
Traceback (most recent call last):
  File "train_ssd.py", line 396, in <module>
    train(train_loader, net, criterion, optimizer, device=DEVICE, debug_steps=args.debug_steps, epoch=epoch)
  File "train_ssd.py", line 133, in train
    for i, data in enumerate(loader):
  File "C:\Users\kvar technologies\anaconda3\envs\Train\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\kvar technologies\anaconda3\envs\Train\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\kvar technologies\anaconda3\envs\Train\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\kvar technologies\anaconda3\envs\Train\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\kvar technologies\anaconda3\envs\Train\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\kvar technologies\anaconda3\envs\Train\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\kvar technologies\anaconda3\envs\Train\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\kvar technologies\anaconda3\envs\Train\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TrainAugmentation.__init__.<locals>.<lambda>'

(Train) D:\Gujarat Fertilizers\Traing\jetson-train-main\jetson-train-main>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\kvar technologies\anaconda3\envs\Train\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\kvar technologies\anaconda3\envs\Train\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by SophieBarriault** [comment]
I have the same exact issue. Did you ever find a solution to this problem?
